#Problem 1-(b)
  "a %in% b" gives the logical value vector of whether each member of a is in b while "a == b" gives the logical value vector of whether sections of a is equal to b when a is divided into sections of length of b(suppose a could be divided, otherwise causes error)
  
#Problem 1-(c)
```{r problem 1-(c)-Example 1: deck}
  library(gtools)
  suits <- c("Diamonds","Clubs","Hearts","Spades")
  numbers <- c("Ace","Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten","Jack","Queen","King")
  deck <- expand.grid(number=numbers, suit=suits);
  deck <- paste(deck$number,deck$suit)
  queens <- paste("Queen",suits)
  S=0
  for(i in 1:4){
    S=S+sum(deck==queens[i])
  }
  S=S/length(deck)
  S
```
#----
```{r problem 1-(c)-Example 1: permutations}
  library(gtools)
  permutations(3,2)
  all_phone_numbers <- permutations(10,7,v=0:9)
  (n<-nrow(all_phone_numbers))
  index<-sample(n,5)
  all_phone_numbers[index,]
  hands<-permutations(52,2,v=deck)
  head(hands)
  nrow(hands)
  first_card<-hands[,1]
  second_card<-hands[,2]
  queens<-paste("Queen",suits)
  S=0
  for(i in 1:4){
    S=S+sum(first_card==queens[i])
  }
  S
  S=S/length(first_card)
  S
  
  res1=rep(FALSE,length(first_card))
  res2=rep(FALSE,length(second_card))
  for(i in 1:4){
    res1=(res1|(first_card==queens[i]))
    res2=(res2|(second_card==queens[i]))
  }
  SS=sum(res1&res2)
  SS=SS/S/length(first_card)
  SS
  SS=SS/(length(first_card)/length(second_card))
  SS
```

```{r problem 1-(c)-Example 2: Blackjack Ace}
  aces<-paste("Ace",suits)
  facecard<-c("King","Queen","Jack","Ten")
  (facecard<-expand.grid(number=facecard,suit=suits))
  facecard<-paste(facecard$number,facecard$suit)
  hands<-combinations(52,2,v=deck)
  
  res1=rep(FALSE,length(hands[,1]))
  res2=rep(FALSE,length(hands[,1]))
  res3=rep(FALSE,length(hands[,2]))
  res4=rep(FALSE,length(hands[,2]))
  for(i in 1:length(aces)){
    res1=(res1|(hands[,1]==aces[i]))
  }
  for(i in 1:length(facecard)){
    res2=(res2|(hands[,1]==facecard[i]))
  }
  for(i in 1:length(aces)){
    res3=(res3|(hands[,2]==aces[i]))
  }
  for(i in 1:length(facecard)){
    res4=(res4|(hands[,2]==facecard[i]))
  }
  SS=mean(res1&res4)
  SS
  SSS=mean((res1&res4)|(res2&res3))
  SSS
```


#Problem 2
```{r problem 2-(a)}
  cat("P(D)=0.25, P(H)=0.75, P(P|D)=0.88, P(N|D)=0.12, P(N|H)=0.90, P(P|H)=0.10\n")
```
#----
```{r problem 2-(b)}
  simulate_test<-function(n){
    set.seed(5)
    is_covid=(runif(n)<0.25)
    is_positive=rep(FALSE,n)
    #set.seed(10)
    is_positive[is_covid]<-(runif(sum(is_covid))<0.88)
    #set.seed(15)
    is_positive[!is_covid]<-(runif(sum(!is_covid))<0.10)
    return(mean(is_positive))
  }
  simulate_test(1000000)
```
#----
```{r problem 2-(c)}
  n=1000000
  is_covid=sample(c(0,1),n,replace=TRUE,prob=c(0.5,0.5));
  is_covid[1:20]
```
#----
```{r problem 2-(d)}
  cat("The probability of testing-positive",0.25*0.88+0.75*0.10,'\n')
  simulate_test_d<-function(n){
    set.seed(5)
    is_covid=(runif(n)<0.25)
    is_positive=rep(FALSE,n)
    #set.seed(10)
    is_positive[is_covid]<-(runif(sum(is_covid))<0.88)
    #set.seed(15)
    is_positive[!is_covid]<-(runif(sum(!is_covid))<0.10)
    return(mean(is_positive))
  }
  simulate_test_d(1000000)
```
#----
```{r problem 2-(e)}
  cat("The conditional probability of P(D|P)",0.25*0.88/(0.25*0.88+0.75*0.10),'\n')
  simulate_test_e<-function(n){
    set.seed(5)
    is_covid=(runif(n)<0.25)
    is_positive=rep(FALSE,n)
    #set.seed(10)
    is_positive[is_covid]<-(runif(sum(is_covid))<0.88)
    #set.seed(15)
    is_positive[!is_covid]<-(runif(sum(!is_covid))<0.10)
    return(mean(is_positive&is_covid)/mean(is_positive))
  }
  simulate_test_e(1000000)
```
#----
```{r problem 2-(f)}
  cat("The conditional probability of P(D|N)",0.25*0.12/(0.25*0.12+0.75*0.90),'\n')
  simulate_test_f<-function(n){
    set.seed(5)
    is_covid=(runif(n)<0.25)
    is_positive=rep(FALSE,n)
    #set.seed(10)
    is_positive[is_covid]<-(runif(sum(is_covid))<0.88)
    #set.seed(15)
    is_positive[!is_covid]<-(runif(sum(!is_covid))<0.10)
    return(mean((!is_positive)&is_covid)/mean(!is_positive))
  }
  simulate_test_f(1000000)
```
#----
```{r problem 2-(g)}
  cat("The conditional probability of P(D|P)-P(D)",0.25*0.88/(0.25*0.88+0.75*0.10)-0.25,'\n')
  simulate_test_g<-function(n){
    set.seed(5)
    is_covid=(runif(n)<0.25)
    is_positive=rep(FALSE,n)
    #set.seed(10)
    is_positive[is_covid]<-(runif(sum(is_covid))<0.88)
    #set.seed(15)
    is_positive[!is_covid]<-(runif(sum(!is_covid))<0.10)
    return(mean(is_positive&is_covid)/mean(is_positive)-0.25)
  }
  simulate_test_g(1000000)
```